export const FETCH_ADDRESSES_REQUEST = "FETCH_ADDRESSES_REQUEST"
export const SUCCESS_ADDRESSES_REQUEST = "SUCCESS_ADDRESSES_REQUEST"
export const FAILED_ADDRESSES_REQUEST = "FAILED_ADDRESSES_REQUEST"