export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST"
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS"
export const FETCH_NOTIFICATIONS_FAILED = "FETCH_NOTIFICATIONS_FAILED"

export const ADD_NOTIFICATIONS_REQUEST = "ADD_NOTIFICATIONS_REQUEST"
export const ADD_NOTIFICATIONS_SUCCESS = "ADD_NOTIFICATIONS_SUCCESS"
export const ADD_NOTIFICATIONS_FAILED = "ADD_NOTIFICATIONS_FAILED"