export const FETCH_ORDER_REQUEST_BY_ID = "FETCH_ORDER_REQUEST_BY_ID"
export const SUCCESS_ORDER_REQUEST_BY_ID = "SUCCESS_ORDER_REQUEST_BY_ID"
export const FAILED_ORDER_REQUEST_BY_ID = "FAILED_ORDER_REQUEST_BY_ID"

export const REQUEST_ORDER_UPDATE = "REQUEST_ORDER_UPDATE"
export const SUCCESS_ORDER_UPDATE = "SUCCESS_ORDER_UPDATE"
export const FAILED_ORDER_UPDATE = "FAILED_ORDER_UPDATE"