export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST"
export const SUCCESS_ORDERS_REQUEST = "SUCCESS_ORDERS_REQUEST"
export const FAILED_ORDERS_REQUEST = "FAILED_ORDERS_REQUEST"

export const FETCH_LIMITED_ORDERS_REQUEST = "FETCH_LIMITED_ORDERS_REQUEST"
export const SUCCESS_LIMITED_ORDERS_REQUEST = "SUCCESS_LIMITED_ORDERS_REQUEST"
export const FAILED_LIMITED_ORDERS_REQUEST = "FAILED_LIMITED_ORDERS_REQUEST"