export const FETCH_POSTCODE_REQUEST = "FETCH_POSTCODE_REQUEST"
export const FETCH_POSTCODE_SUCCESS = "FETCH_POSTCODE_SUCCESS"
export const FETCH_POSTCODE_FAILED = "FETCH_POSTCODE_FAILED"

export const ADD_POSTCODE_REQUEST = "ADD_POSTCODE_REQUEST"
export const ADD_POSTCODE_SUCCESS = "ADD_POSTCODE_SUCCESS"
export const ADD_POSTCODE_FAILED = "ADD_POSTCODE_FAILED"