const tableData = [
    {
        skew: 'sw-tc-pn-2j-9x',
        name: 'Chicken Pieced',
        price: 19.99,
        email: 'hellobutcher@gmail.com',
        sold: 7,
        remain: 15,
        date: '19 feb 2020',
        status: 'success',
    },
    {
        skew: 'sw-tc-pn-do-9x',
        name: 'Chicken Sliced',
        price: 29.99,
        email: 'sakilahmmad71@gmail.com',
        sold: 9,
        remain: 10,
        date: '20 feb 2020',
        status: 'pending',
    },
    {
        skew: 'pq-tc-fr-ot-9x',
        name: 'Chicken Chop',
        title: 'Chicken Chop for whole family',
        price: 9.99,
        email: 'hellobutcher.co.uk@gmail.com',
        sold: 12,
        remain: 15,
        date: '19 mar 2020',
        status: 'success',
    },
    {
        skew: 'qr-bg-pn-ty-9x',
        name: 'Beef Pieced',
        title: 'Beef Pieced for whole family',
        price: 29.99,
        email: 'sklmario12@gmail.com',
        sold: 5,
        remain: 12,
        date: '21 may 2020',
        status: 'success',
    },
    {
        skew: 'ae-sd-pn-ds-df',
        name: 'Beef Sliced',
        title: 'Beef Sliced for whole family',
        price: 19.99,
        email: 'sakil123@gmail.com',
        sold: 7,
        remain: 16,
        date: '29 aug 2020',
        status: 'pending',
    },
    {
        skew: 'fg-oc-jun-7j-9x',
        name: 'Beef Mutton',
        title: 'Beef Mutton for whole family',
        price: 9.99,
        email: 'helloworld@gmail.com',
        sold: 6,
        remain: 12,
        date: '22 dec 2020',
        status: 'pending',
    },
    {
        skew: 'as-tc-vf-ff-sd',
        name: 'Sheep Sliced',
        title: 'Sheep Sliced for whole family',
        price: 18.99,
        email: 'sulaiman@gmail.com',
        sold: 7,
        remain: 29,
        date: '21 mar 2020',
        status: 'success',
    },
    {
        skew: 'vf-tc-we-df-9x',
        name: 'Sheep Pieced',
        title: 'Sheep Pieced for whole family',
        price: 18.99,
        email: 'sumonuk1200@gmail.com',
        sold: 29,
        remain: 30,
        date: '23 jun 2020',
        status: 'pending',
    },
];

export default tableData;
